### ISSUE TITLE
bug in bash getops

### ISSUE THREAD

**Issue by cazaudo** [Project-OSmOSE/osmose-toolkit#34]
on datarmor at least we get the following error with the legacy reshaping : 

  File "/home/datawork-osmose/osmose_package_dev/src/OSmOSE/cluster/reshaper.sh", line 5
    d)
     ^
SyntaxError: unmatched ')'

**Comment by Rumengol** [comment]
It might be an opportunity to discuss if we should drop the legacy method altogether. Since the resampling and reshaping steps are separated, I am not sure if it is worth to maintain two methods to do the same thing, especially if one of them is more limited.
