### ISSUE TITLE
Adding depth of hydrophone in metada.

### ISSUE THREAD

**Issue by gmanatole** [Project-OSmOSE/osmose-toolkit#73]
So far only latitude and longitude values are saved in metadata.csv
However depth is an important parameter when analyzing audio.

**Comment by cazaudo** [comment]
hello @gmanatole and @MaelleTtrt 
i am starting working on this issue to integrate depth info at dataset building , different cases :
- depth is a single value for fixed hydro , we put it in metadata.csv , no pb
- if depth is time variable for moving hydro ? i suggest we can put a _filename_depth_.csv file along wav files , and we automatically put it in /data/auxiliary/instrument , ok ? its filename must be passed in the notebook
