### ISSUE TITLE
create a _SUCESS file in folder of spectrograms to ensure processing finished correctly

### ISSUE THREAD

**Issue by Rumengol** [Project-OSmOSE/osmose-toolkit#76]
for the moment after closing the notebook the user does not have any way to be sure that all spectrograms for example have been successfully generated

solution : create a light job counting generated files and check the number is correct , this job should come last , ie be dependent on all processing job

**Comment by cazaudo** [comment]
after discussion : do not launch a job , just print generated spectros and count them within each job , print a success status per job
